import type { TicketStats, TicketSummary } from "@/lib/api/types";
import { asIsoDateTimeString } from "@/lib/datetime/iso";

export const dashboardStatsFixture: TicketStats = {
  new: 4,
  inProgress: 12,
  pending: 3,
  solved: 28,
  solvedRecent: 19,
  total: 19,
  totalOpen: 19,
};

export const dashboardTicketsFixture: TicketSummary[] = [
  {
    id: 13741,
    title: "Equipe inteira sem acesso ao sistema de protocolo",
    content: "Relato coletivo de indisponibilidade para a equipe do protocolo na Casa Civil.",
    category: "Rede > Acesso",
    status: "Novo",
    statusId: 1,
    urgency: "Alta",
    urgencyId: 4,
    dateCreated: asIsoDateTimeString("2026-04-11T08:10:00Z"),
    dateModified: asIsoDateTimeString("2026-04-11T08:12:00Z"),
    requester: "Jonathan Moletta",
    technician: "Triagem DTIC",
    groupName: "CC > SUBADM > DTIC > N3",
    slaTime: "00:37",
  },
  {
    id: 13742,
    title: "Reset de senha do SEI para novo servidor",
    content: "Usuario recem-alocado precisa acessar o SEI ainda hoje para assinatura de processo.",
    category: "Acesso > SEI",
    status: "Novo",
    statusId: 1,
    urgency: "Media",
    urgencyId: 3,
    dateCreated: asIsoDateTimeString("2026-04-11T08:28:00Z"),
    dateModified: asIsoDateTimeString("2026-04-11T08:30:00Z"),
    requester: "Carla Lopes",
    technician: "Fila DTIC",
    groupName: "CC > SUBADM > DTIC > N2",
  },
  {
    id: 13738,
    title: "Erro 500 ao assinar processo no SEI",
    content: "Chamado em analise com suspeita de falha intermitente no servico do SEI.",
    category: "Aplicacao > SEI",
    status: "Em Atendimento",
    statusId: 2,
    urgency: "Alta",
    urgencyId: 4,
    dateCreated: asIsoDateTimeString("2026-04-11T07:15:00Z"),
    dateModified: asIsoDateTimeString("2026-04-11T08:04:00Z"),
    requester: "Marina Araujo",
    technician: "Equipe N3",
    groupName: "CC > SUBADM > DTIC > N3",
    slaTime: "00:11",
  },
  {
    id: 13735,
    title: "VPN instavel para equipe da assessoria",
    content: "Atendimento em andamento com coleta de logs e validacao de conectividade.",
    category: "Rede > VPN",
    status: "Planejado",
    statusId: 3,
    urgency: "Alta",
    urgencyId: 4,
    dateCreated: asIsoDateTimeString("2026-04-11T06:42:00Z"),
    dateModified: asIsoDateTimeString("2026-04-11T07:56:00Z"),
    requester: "Bruno Lemos",
    technician: "Equipe N2",
    groupName: "CC > SUBADM > DTIC > N2",
  },
  {
    id: 13729,
    title: "Notebook sem webcam para videoconferencia",
    content: "Solicitante aguarda troca ou liberacao de equipamento equivalente para reuniao externa.",
    category: "Hardware > Notebook",
    status: "Pendente",
    statusId: 4,
    urgency: "Media",
    urgencyId: 3,
    dateCreated: asIsoDateTimeString("2026-04-10T17:10:00Z"),
    dateModified: asIsoDateTimeString("2026-04-11T08:00:00Z"),
    requester: "Renata Alves",
    technician: "Suporte Local",
    groupName: "CC > SUBADM > DTIC > Campo",
  },
  {
    id: 13718,
    title: "Impressora do gabinete voltou a responder",
    content: "Equipamento reconfigurado e estabilizado apos limpeza de fila e reinicio controlado.",
    category: "Perifericos > Impressora",
    status: "Solucionado",
    statusId: 5,
    urgency: "Baixa",
    urgencyId: 2,
    dateCreated: asIsoDateTimeString("2026-04-10T13:05:00Z"),
    dateModified: asIsoDateTimeString("2026-04-11T06:30:00Z"),
    requester: "Andreia Ribeiro",
    technician: "Equipe N1",
    groupName: "CC > SUBADM > DTIC > N1",
  },
];

export const dashboardFilteredTicketsFixture = dashboardTicketsFixture.filter((ticket) =>
  [13741, 13738].includes(ticket.id),
);
